### ISSUE TITLE
3D Rotation

### ISSUE THREAD

**Issue by jmweeks101** [jmweeks101/Graphics3#8]
Find a way to rotate a 3D object and project it in 2D space.

**Comment by sojdb** [comment]
I've researched the topic of 3 dimensions just a little bit, but from what I've seen we cannot really determine a Z coordinate from just the X and Y coordinates. Due to this, we wouldn't be able to do the proper '3D rotation'' unless a Z coordinate is specified. I thought of using the 2D rotation for every face, but it still isn't technically a 3D rotation, but it will still rotate it. The one thing with the  3D rotation as well is that we do not create every face when creating the 3D shape, so when rotating, how will the other faces  be shown (such as the ones that are behind the original view)? I thought of potentially using the 2D rotation in a for loop, however that isn't technically a '3D rotation', however it should still rotate the 3D object in at least one of the dimensions (rather than the two that the 3D rotation would perform).
